### ISSUE TITLE
java.lang.ClassCastException: 

### ISSUE THREAD

**Issue by ameerhamza6733** [iamvaliyev/GiggleViewRecorder#1]
how to slove this error 
**`    java.lang.ClassCastException: android.app.ContextImpl cannot be cast to az.giggle.giggleviewrecorder.manager.BaseApplication`**

i parsing context some thing like this

  record.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                if (!captureHelper.isRecording()) {

                    RecorderSettings recorderSettings = new RecorderSettings(view);
                    recorderSettings.setWithDuration(true);
                    recorderSettings.setDuration(10);

                    captureHelper.startRecordView((BaseApplication) getBaseContext(), recorderSettings, new RecordingSession.Listener() {
                        @Override
                        public void onStart() {
                            ColorDrawable[] color = {new ColorDrawable(Color.BLUE), new ColorDrawable(Color.RED)};

                            TransitionDrawable trans = new TransitionDrawable(color);
                            view.setBackgroundDrawable(trans);
                            trans.startTransition(10000);
                        }

                        @Override
                        public void onStop() {

                        }

                        @Override
                        public void onError(String error) {

                        }

                        @Override
                        public void onEnd(String path) {

                        }
                    });

**Comment by iamvaliyev** [comment]
This error in demo project ?

**Comment by ameerhamza6733** [comment]
Wrong 1st argument type. Found: 'android.app.Application', required: 'az.giggle.giggleviewrecorder.manager.BaseApplication' . it when i try to ad your line of code inside my onCreat()

**Comment by alimOctagon** [comment]
I found the same problem here! I think the problem is because iamvaliyev use a modified 'Application' class called 'BaseApplication'. If my guess is correct, I suppose we cannot use your code until you use the default 'Application' class instead.

Do you have any plan to modify this GiggleViewRecorder so we can use it with default classes?

**Comment by iamvaliyev** [comment]
Project is work. Add Application Class to Manifest and Happy coding)

`<application
android:name="az.giggle.giggleviewrecorder.manager.BaseApplication" />`

**Comment by alimOctagon** [comment]
thanks!

I will give it a try.

Regards,
Alim
Creative Manager
Octagon Studio
